spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_showroom
    username: postgres
    password: 1313
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true